baseURL = ""
languageCode = "en-us"
theme = "stupidity_rocks"
title = "Stupidity Rocks"

disableKinds = ["page", "RSS", "section", "taxonomy", "term"]

[params]
  bannerTitle = "hello,"
  bannerDescription = "You have reached the end of the Internet. You have reach the very last page on the very last server at the very far end of the cloud - the furthest one that you can see when looking up at the sky.<br /><br />There is nothing more to see, no more pages to visit, no more links to follow.<br /><br />You should now turn off your device and go do something useful with the rest of your life."
  copyright = "Copyright &copy; 2020 Frederico Martins"
  favicon = "favicon.ico"
  madein = "Made in PT"
  ribbonText = "stupidity<br />should be painfull"
  rss = false

[minify]
  disableCSS = false
  disableHTML = false
  disableXML = false
  minifyOutput = true

[caches]
  [caches.assets]
    maxAge = "30m"
